apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: hal78/order-service:latest
        ports:
        - containerPort: 4000
        env:
        - name: USE_POSTGRES
          value: "false" # or true if you use it
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: order-service-db-secret
              key: DATABASE_URL
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 20
